name: MySQL Backup

on:
  schedule:
    - cron: "* 23 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install MySQL client
      run: sudo apt-get install mysql-client
    - name: Run backup script
      run: python backup_db.py
